### ISSUE TITLE
Query taking too long

### ISSUE THREAD

**Issue by scripting** [scripting/feedlandInstall#31]
The other day, this query started taking 27 seconds to run on my account, which is longer than the timeout. 

``
select * from items where flDeleted=false  and feedurl in (select feedUrl from subscriptions where listName='davewiner') order by pubDate desc limit 175;
``

It just started happening, and at least one other user is seeing it. It has rendered FeedLand basically useless to me.

Now I'm in over my head as far as MySQL is concerned. Not sure how to debug this, or how to fix the problem. I'm to grind at it but if anyone has an idea how to approach this, help would be most welcome.

**Comment by scripting** [comment]
@scotthansonde -- thank you.

it's so funny, you posted this fix as I was announcing the open source release of The FeedLand Platform. 

so that we could get help with this. ;-)

i'll report on how it affects this issue.

**Comment by scripting** [comment]
@scotthansonde -- before doing anything on the feedland.org database, I want to see how this will be documented on the [database.md](https://github.com/scripting/feedland/blob/main/database/database.md) page. 

At the end we create three indexes: 

```
create index itemFeed on items(feedUrl);
create index itemPubDate on items(pubDate);
create index subscriptionsListname on subscriptions(listname);
```
I propose to add:

`create index itemDeleted on items(flDeleted);`

If this is correct, you can just Like this comment.

**Comment by iolaire** [comment]
Also, in SQL server we do something like this in the exists statement `(select top 1 1 from subscriptions as s where s.listName='davewiner' and  i.feedUrl = s.feedUrl  )` so it doesn't return all the results, it just ends once the first result is hit, so you might also try something like this: `select * from items as i where flDeleted=false  and EXISTS (select 1 from subscriptions as s where s.listName='davewiner' and  i.feedUrl = s.feedUrl LIMIT 1 ) order by pubDate desc limit 175;` and use EXPLAIN to see if that improves things future.

**Comment by scripting** [comment]
@scotthansonde -- it didn't make the query faster, actually i had tried it without the flDeleted part of the query as follows:

`select * from items where feedurl in (select feedUrl from subscriptions where listName='davewiner') order by pubDate desc limit 175;`

And it took 29 seconds. 

So I'm getting different results here (and I should have read your initial comment more carefully).

**Comment by scripting** [comment]
Here's an interesting piece of data.

Somehow I lost my categories in the Settings command, and that's why I'm getting the huge timeout. 

Once I reinstated my categories, things went back to how they were, performing as before. 

https://feedland.org/?river

So this is only affecting people who have no categories, ie newbies.

**Comment by iolaire** [comment]
I've wanted to suggest that doing all those join columns are way less efficient than on an integer-based AUTO_INCREMENT ID column from each table.  So here is the ChatGTP explanation:

_**in mysql is it faster to join on an integer column or a text column**_
In general, joining on an integer column will be faster than joining on a text column in MySQL. This is because integer comparisons are simpler and faster for the database to perform than text comparisons.

When you join on an integer column, the database can use a simple numeric comparison to match the values in the join. This comparison is straightforward and efficient, allowing the database to quickly identify the matching rows.

On the other hand, when you join on a text column, the database needs to perform a string comparison. String comparisons are more complex than integer comparisons, and they can be slower to execute. Additionally, if the text column is indexed, the index size will be larger and more memory-intensive than an index on an integer column, which can also slow down the join performance.

That being said, there may be cases where joining on a text column is necessary or more appropriate. For example, if the values in the column are not easily represented as integers (e.g. names, addresses, or other non-numeric identifiers), joining on a text column may be necessary. Additionally, in some cases, using a text column for a join may allow for more flexibility in how the join is performed.

**Comment by scripting** [comment]
I'm going to take a fresh look at this tomorrow. To prepare for it, I went through the problem with ChatGPT.

http://scripting.com/publicfolder/chatgpt/2023/04/24/mysql-database-assistance.html

**Comment by mterenzio** [comment]
There are a number of long term changes to the modeling that I think would improve performance and ease of maintenance. Some have been mentioned like indexes, serial columns but also unique constraints and  foreign keys, but these would also likely require code changes and query rewrites.

That said, in my experience with queries that suddenly start performing poorly, a surprising amount of time it also reflects not being able to fit the data set into memory. In other words, the table outgrew the available memory and is needing to go to disk. 

Without more information, I can't say if that's the case, but thought it was worth a quick try, especially if you are on a cloud based system where adding RAM is just a few clicks.

Or before doing that, while the query is running, run the `free` command and note the memory and swap usage. I believe I recall you are on linux.

**Comment by scripting** [comment]
Thanks @mterenzio -- yes this is running on Ubuntu, hosted at Digital Ocean.

**Comment by scripting** [comment]
I'm getting a late start today, but I'm determined to fix this problem now because I have a juicy project I can't wait to get back to. 

So here's the query -- 

select * from items where flDeleted=false  and feedurl in (select feedUrl from subscriptions where listName='mrjones') order by pubDate desc limit 175;

That's the query we do for users who have no categories in the Settings dialog. Here's the [screen shot](https://user-images.githubusercontent.com/1686843/234351853-1d1504d7-c9da-419f-9456-68f488e0f83a.png)) to really bring that home. 

**As soon as you add categories, the problem goes away.** 

If so, the problem might have been happening to newbies, who have no categories to start off with, and we just weren't hearing about it because all the users we're in contact with have categories?

I only saw this behavior myself when, due to a glitch, I lost my categories (a completely separate issue).

So the big question is, what's the difference in the query we use when getting the new items for a user with categories?

To be clear, we're only retrieving the category that's selected. You can see the delay if you click on a tab.

**Comment by scripting** [comment]
This query runs fast. It's what we run when we're displaying a category in a tabbed display. I'm going to study this and see if it's possible to use the same approach for category-less users. 

select * from items where flDeleted=false  and feedurl in ('http://nytimes.com/timeswire/feeds/','http://rss.nytimes.com/services/xml/rss/nyt/Baseball.xml','http://rss.nytimes.com/services/xml/rss/nyt/ProBasketball.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/bret-stephens/rss.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/charles-m-blow/rss.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/david-brooks/rss.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/ezra-klein/rss.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/farhad-manjoo/rss.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/frank-bruni/rss.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/gail-collins/rss.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/jamelle-bouie/rss.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/maureen-dowd/rss.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/michelle-goldberg/rss.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/nicholas-kristof/rss.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/paul-krugman/rss.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/ross-douthat/rss.xml','http://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/thomas-l-friedman/rss.xml','https://donaldgmcneiljr1954.medium.com/feed','https://feeds.simplecast.com/54nAGcIl','https://rss.nytimes.com/services/xml/rss/nyt/Africa.xml','https://rss.nytimes.com/services/xml/rss/nyt/Americas.xml','https://rss.nytimes.com/services/xml/rss/nyt/ArtandDesign.xml','https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml','https://rss.nytimes.com/services/xml/rss/nyt/AsiaPacific.xml','https://rss.nytimes.com/services/xml/rss/nyt/Automobiles.xml','https://rss.nytimes.com/services/xml/rss/nyt/Baseball.xml','https://rss.nytimes.com/services/xml/rss/nyt/Books.xml','https://rss.nytimes.com/services/xml/rss/nyt/Business.xml','https://rss.nytimes.com/services/xml/rss/nyt/Climate.xml','https://rss.nytimes.com/services/xml/rss/nyt/CollegeBasketball.xml','https://rss.nytimes.com/services/xml/rss/nyt/CollegeFootball.xml','https://rss.nytimes.com/services/xml/rss/nyt/Dance.xml','https://rss.nytimes.com/services/xml/rss/nyt/Dealbook.xml','https://rss.nytimes.com/services/xml/rss/nyt/DiningandWine.xml','https://rss.nytimes.com/services/xml/rss/nyt/EnergyEnvironment.xml','https://rss.nytimes.com/services/xml/rss/nyt/Europe.xml','https://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml','https://rss.nytimes.com/services/xml/rss/nyt/Golf.xml','https://rss.nytimes.com/services/xml/rss/nyt/Hockey.xml','https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml','https://rss.nytimes.com/services/xml/rss/nyt/Jobs.xml','https://rss.nytimes.com/services/xml/rss/nyt/Lens.xml','https://rss.nytimes.com/services/xml/rss/nyt/MediaandAdvertising.xml','https://rss.nytimes.com/services/xml/rss/nyt/MiddleEast.xml','https://rss.nytimes.com/services/xml/rss/nyt/MostEmailed.xml','https://rss.nytimes.com/services/xml/rss/nyt/Movies.xml','https://rss.nytimes.com/services/xml/rss/nyt/Music.xml','https://rss.nytimes.com/services/xml/rss/nyt/NYRegion.xml','https://rss.nytimes.com/services/xml/rss/nyt/Obituaries.xml','https://rss.nytimes.com/services/xml/rss/nyt/PersonalTech.xml','https://rss.nytimes.com/services/xml/rss/nyt/ProBasketball.xml','https://rss.nytimes.com/services/xml/rss/nyt/ProFootball.xml','https://rss.nytimes.com/services/xml/rss/nyt/RealEstate.xml','https://rss.nytimes.com/services/xml/rss/nyt/Science.xml','https://rss.nytimes.com/services/xml/rss/nyt/SmallBusiness.xml','https://rss.nytimes.com/services/xml/rss/nyt/Soccer.xml','https://rss.nytimes.com/services/xml/rss/nyt/Space.xml','https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml','https://rss.nytimes.com/services/xml/rss/nyt/sunday-review.xml','https://rss.nytimes.com/services/xml/rss/nyt/SundayBookReview.xml','https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml','https://rss.nytimes.com/services/xml/rss/nyt/Television.xml','https://rss.nytimes.com/services/xml/rss/nyt/Tennis.xml','https://rss.nytimes.com/services/xml/rss/nyt/Theater.xml','https://rss.nytimes.com/services/xml/rss/nyt/tmagazine.xml','https://rss.nytimes.com/services/xml/rss/nyt/Upshot.xml','https://rss.nytimes.com/services/xml/rss/nyt/US.xml','https://rss.nytimes.com/services/xml/rss/nyt/Well.xml','https://rss.nytimes.com/services/xml/rss/nyt/World.xml','https://rss.nytimes.com/services/xml/rss/nyt/YourMoney.xml','https://www.nytimes.com/services/xml/rss/nyt/Health.xml','https://www.nytimes.com/services/xml/rss/nyt/Travel.xml','https://www.nytimes.com/services/xml/rss/nyt/Weddings.xml') order by pubDate desc limit 175;

**Comment by mterenzio** [comment]
I bet that would be your best bet for now, splitting it up into two queries, first getting the results from the sub query (in the parentheses) and adding the result as an array or comma separated list of strings to the the other part of the query.
May be an issue if it gets really, really big so you may need to add a limit of some sort to the first query

**Comment by scripting** [comment]
BTW if anyone wants to get an idea how the pieces fit together, I just updated the FeedLand platform source.

https://github.com/scripting/feedland

Changes were made to 

1. [database/database.js](https://github.com/scripting/feedland/blob/main/database/database.js#L1547)
2. [feedland.js](https://github.com/scripting/feedland/blob/main/feedland.js#L659)
